#!/bin/bash
set -e

echo "🔧 Installing AI Agent System..."

# ============================================
# 1. СОЗДАЁМ СТРУКТУРУ
# ============================================
mkdir -p .agent-system/templates

# ============================================
# 2. CONFIG
# ============================================
cat > .agent-system/config.sh << 'EOF'
#!/bin/bash
export SMART_MODEL="groq/llama-3.3-70b-versatile"
export FAST_MODEL="groq/llama-3.1-8b-instant"
export MAX_RETRY=3
export GROQ_COOLDOWN=12
EOF

# ============================================
# 3. TEMPLATES
# ============================================
cat > .agent-system/templates/gitignore << 'EOF'
__pycache__/
*.py[cod]
*.so
.Python
venv/
env/
.env
*.egg-info/
dist/
build/
.pytest_cache/
.mypy_cache/
*.log
.DS_Store
node_modules/
.agent/
EOF

# ============================================
# 4. ГЛАВНЫЙ СКРИПТ АГЕНТА
# ============================================
cat > .agent-system/agent.sh << 'AGENT'
#!/bin/bash
set -e

# Цвета
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'; N='\033[0m'

# Логи
log()  { echo -e "${C}[$(date +%H:%M:%S)]${N} $1"; }
ok()   { echo -e "${G}✅ $1${N}"; }
warn() { echo -e "${Y}⚠️  $1${N}"; }
fail() { echo -e "${R}❌ $1${N}"; exit 1; }
step() { echo -e "\n${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n${B}  $1${N}\n${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"; }

# Загружаем конфиг
source ~/.agent/config.sh 2>/dev/null || {
    export SMART_MODEL="groq/llama-3.3-70b-versatile"
    export FAST_MODEL="groq/llama-3.1-8b-instant"
    export MAX_RETRY=3
    export GROQ_COOLDOWN=12
}

# ============================================
# ВАЛИДАЦИЯ ВХОДА
# ============================================
PROMPT="$*"
if [ -z "$PROMPT" ]; then
    echo "Usage: agent \"короткое описание проекта\""
    echo ""
    echo "Примеры:"
    echo "  agent \"Python calculator CLI\""
    echo "  agent \"Telegram weather bot\""
    echo "  agent \"Habr news parser with SQLite\""
    exit 1
fi

# Генерация имени проекта
PROJECT_NAME=$(echo "$PROMPT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9 ]//g' | tr ' ' '-' | cut -c1-40)
WORKDIR="/workspaces/$PROJECT_NAME"

log "🤖 Agent started"
log "📋 Task: $PROMPT"
log "📁 Project: $PROJECT_NAME"
log "📍 Location: $WORKDIR"

# Создаём рабочую директорию
mkdir -p "$WORKDIR"
cd "$WORKDIR"

# Инициализируем git (если нет)
if [ ! -d ".git" ]; then
    git init
    git config user.name "AI Agent"
    git config user.email "agent@localhost"
fi

# Создаём папку для логов
mkdir -p .agent
LOG_FILE=".agent/agent.log"
echo "=== Agent Log ===" > "$LOG_FILE"
echo "Started: $(date)" >> "$LOG_FILE"
echo "Task: $PROMPT" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

# ============================================
# PHASE 1: PLANNING
# ============================================
phase_plan() {
    step "PHASE 1/4: PLANNING"
    log "🧠 AI analyzing task..."
    
    sleep 2  # Даём время прочитать
    
    aider \
        --model "$SMART_MODEL" \
        --yes \
        --no-auto-commits \
        --message "You are a senior software architect. Analyze this task and create a plan.

TASK: $PROMPT

Create a file called 'PLAN.md' with:

# Project Plan

## Summary
(2-3 sentences about what this does)

## Tech Stack
- Language: (Python/JavaScript/etc)
- Key libraries: (list main dependencies)

## File Structure
\`\`\`
project/
├── main file
├── helper files
└── tests
\`\`\`

## Core Functions
1. Function 1: description
2. Function 2: description

Keep it CONCISE (under 60 lines)." 2>&1 | tee -a "$LOG_FILE"

    if [ ! -f "PLAN.md" ]; then
        fail "Planning failed - PLAN.md not created"
    fi
    
    ok "Plan created: PLAN.md"
    sleep "$GROQ_COOLDOWN"
}

# ============================================
# PHASE 2: SCAFFOLDING
# ============================================
phase_scaffold() {
    step "PHASE 2/4: SCAFFOLDING"
    log "📁 Creating project structure..."
    
    # Создаём базовую структуру
    mkdir -p src tests
    
    # Копируем .gitignore
    if [ -f "$HOME/.agent/templates/gitignore" ]; then
        cp "$HOME/.agent/templates/gitignore" .gitignore
    else
        echo "__pycache__/" > .gitignore
        echo "*.pyc" >> .gitignore
        echo ".env" >> .gitignore
        echo "venv/" >> .gitignore
    fi
    
    # Создаём README
    cat > README.md << README
# $PROJECT_NAME

Auto-generated by AI Agent

## Task
$PROMPT

## Setup
See PLAN.md for details
README
    
    git add -A
    git commit -m "chore: initial scaffold" 2>/dev/null || true
    
    ok "Structure created"
}

# ============================================
# PHASE 3: IMPLEMENTATION
# ============================================
phase_implement() {
    step "PHASE 3/4: IMPLEMENTATION"
    log "⚡ AI writing code..."
    
    aider \
        --model "$SMART_MODEL" \
        --yes \
        --message "Implement the project based on PLAN.md.

RULES:
1. Create ALL necessary files (main code, helpers, tests)
2. Write COMPLETE, WORKING code (no TODOs or placeholders)
3. Add error handling
4. Add docstrings/comments
5. For Python: use type hints
6. Create requirements.txt (Python) or package.json (Node)

Be professional and thorough." 2>&1 | tee -a "$LOG_FILE"
    
    ok "Implementation complete"
    sleep "$GROQ_COOLDOWN"
}

# ============================================
# PHASE 4: TESTING & FIXING
# ============================================
phase_test() {
    step "PHASE 4/4: TESTING"
    log "🧪 Running tests..."
    
    # Определяем тип проекта и пытаемся запустить тесты
    TEST_CMD=""
    if [ -f "requirements.txt" ]; then
        log "Installing Python dependencies..."
        python3 -m pip install -q -r requirements.txt 2>&1 | tail -3
        python3 -m pip install -q pytest 2>&1 | tail -1
        TEST_CMD="python3 -m pytest tests/ -v"
    elif [ -f "package.json" ]; then
        log "Installing Node dependencies..."
        npm install 2>&1 | tail -3
        TEST_CMD="npm test"
    else
        warn "No test framework detected, skipping tests"
        return 0
    fi
    
    # Пытаемся запустить тесты с автофиксом
    for attempt in $(seq 1 $MAX_RETRY); do
        log "Test attempt $attempt/$MAX_RETRY..."
        
        if $TEST_CMD 2>&1 | tee .agent/test_output.log; then
            ok "All tests passed on attempt $attempt!"
            return 0
        fi
        
        if [ $attempt -lt $MAX_RETRY ]; then
            warn "Tests failed, asking AI to fix..."
            
            ERROR_LOG=$(tail -50 .agent/test_output.log)
            
            aider \
                --model "$SMART_MODEL" \
                --yes \
                --message "Tests failed with these errors:

\`\`\`
$ERROR_LOG
\`\`\`

Fix the SOURCE CODE (not the tests unless they're clearly wrong).
Make tests pass." 2>&1 | tee -a "$LOG_FILE"
            
            sleep "$GROQ_COOLDOWN"
        fi
    done
    
    warn "Tests still failing after $MAX_RETRY attempts"
    warn "Check .agent/test_output.log for details"
    return 1
}

# ============================================
# MAIN EXECUTION
# ============================================
main() {
    phase_plan
    phase_scaffold
    phase_implement
    phase_test
    
    # Финальный коммит
    git add -A
    git commit -m "feat: $PROMPT" 2>/dev/null || true
    
    # Создаём GitHub репо (если gh установлен)
    if command -v gh &> /dev/null; then
        log "Creating GitHub repository..."
        gh repo create "$PROJECT_NAME" --public --source=. --remote=origin --push 2>/dev/null && \
            ok "Pushed to GitHub: https://github.com/$(gh api user -q .login)/$PROJECT_NAME" || \
            warn "GitHub push failed (run 'gh auth login' first)"
    fi
    
    echo ""
    echo -e "${G}╔══════════════════════════════════════════╗${N}"
    echo -e "${G}║         🎉 PROJECT COMPLETE              ║${N}"
    echo -e "${G}╠══════════════════════════════════════════╣${N}"
    echo -e "${G}║${N}  📁 Location: $WORKDIR"
    echo -e "${G}║${N}  📄 Files: $(find . -type f ! -path './.git/*' ! -path './.agent/*' | wc -l)"
    echo -e "${G}║${N}  📋 Plan: PLAN.md"
    echo -e "${G}║${N}  📊 Log: .agent/agent.log"
    echo -e "${G}╚══════════════════════════════════════════╝${N}"
    echo ""
}

main
AGENT

chmod +x .agent-system/agent.sh

# ============================================
# 5. ОБНОВЛЯЕМ .BASHRC
# ============================================
cat > .bashrc << 'BASHRC'
# ==========================================
# 🤖 AI AGENT SYSTEM
# ==========================================

export PATH="$HOME/.local/bin:$PATH"
export GROQ_API_KEY="YOUR_KEY_HERE"

# НАВИГАЦИЯ
alias cs='gh codespace ssh'
alias repos='ls -la /workspaces/'

repo() {
    if [ -z "$1" ]; then
        echo "📂 Repos:"; ls -1 /workspaces/; return
    fi
    cd "/workspaces/$1" && pwd && git status --short
}

# GIT
alias gs='git status'
alias ga='git add -A'
alias gp='git push'
alias gl='git log --oneline -10'

save() {
    git add -A && git commit -m "${1:-wip}" && git push 2>/dev/null
}

# AI COMMANDS
alias ai='aider --model groq/llama-3.1-8b-instant --dark-mode --auto-commits --yes'
alias aia='aider --model groq/llama-3.3-70b-versatile --architect --dark-mode --yes'

agent() {
    if [ ! -f "$HOME/.agent/agent.sh" ]; then
        echo "❌ Agent not installed. Run: bash /workspaces/The-AI-Corporation/install.sh"
        return 1
    fi
    bash "$HOME/.agent/agent.sh" "$@"
}

# AUTO-RESTORE
if [ ! -d "$HOME/.agent" ] && [ -f "/workspaces/The-AI-Corporation/install.sh" ]; then
    bash /workspaces/The-AI-Corporation/install.sh > /dev/null 2>&1
fi

alias sync-system='bash /workspaces/The-AI-Corporation/install.sh'

help-ai() {
    echo "
    ╔══════════════════════════════════════╗
    ║        🤖 AI AGENT SYSTEM            ║
    ╠══════════════════════════════════════╣
    ║  agent \"task\"  — автономный агент   ║
    ║  ai            — aider быстрый       ║
    ║  aia           — aider умный         ║
    ║  repo          — перейти в репо      ║
    ║  save          — commit + push       ║
    ║  sync-system   — обновить систему    ║
    ╚══════════════════════════════════════╝
    "
}

echo "💡 help-ai — список команд"
BASHRC

# ============================================
# 6. ОБНОВЛЯЕМ INSTALL.SH
# ============================================
cat > install.sh << 'INSTALL'
#!/bin/bash
set -e
echo "🔄 Installing AI Agent System..."

# Проверяем наличие aider
if ! command -v aider &> /dev/null; then
    pip install -q aider-chat
fi

# Копируем файлы
cp .bashrc ~/.bashrc
cp -r .agent-system ~/.agent

# Права на выполнение
chmod +x ~/.agent/agent.sh

# Применяем bashrc
source ~/.bashrc

echo "✅ Done! Type: help-ai"
INSTALL

chmod +x install.sh

# ============================================
# 7. СОХРАНЯЕМ В GIT
# ============================================
git add -A
git commit -m "feat: complete working agent system"
git push

# ============================================
# 8. УСТАНАВЛИВАЕМ
# ============================================
bash install.sh

echo ""
echo "✅ AGENT SYSTEM INSTALLED"
echo ""
echo "Test it:"
echo "  agent \"Python calculator CLI\""
echo ""
